export declare function el(type: string, className?: string, parent?: HTMLElement): HTMLElement;
export declare function webgl(): boolean;
export declare function getDocumentHeight(): number;
export declare function isMobile(): boolean;
export declare function isBrowser(vendor: string): boolean;
export declare function isSafari(): boolean;
export declare function getAndroidVersion(): number;
export declare function isIphone(): boolean;
export declare function isIpad(): boolean;
export declare function getIOSVersion(): number;
export declare function isDesktop(): boolean;
export declare function isTouchDevice(): boolean;
export declare function hasGetUserMedia(): boolean;
export declare function copyToClipboard(str: string): void;
